# PDM driver
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y

# USB related configs
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Zephyr USB Audio Test Device"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n

# LOG subsystem related configs
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y

CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y

CONFIG_CBPRINTF_FP_SUPPORT=y

# net buf options
CONFIG_NET_BUF=y

# USB audio related configs
CONFIG_USB_DEVICE_AUDIO=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_RING_BUFFER=y

# TMI pressure driver
CONFIG_TMI_DRV_XGZP68=y

# Timer
CONFIG_COUNTER=y
CONFIG_TIMING_FUNCTIONS=y